(() => {
  'use strict';
  const V = window.VocabularyMaster = window.VocabularyMaster || {};
  const uid = () => `vocab-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const esc = s => { const d=document.createElement('div'); d.textContent=String(s ?? ''); return d.innerHTML; };
  const arr = v => Array.isArray(v) ? v : String(v || '').split(',').map(x=>x.trim()).filter(Boolean);
  const now = () => Date.now();
  const state = { filter:'all', category:'All', search:'', detail:null, practice:null, exam:null };
  let records = [];
  const samples = [
    ['abate','কমানো','to make something less intense or widespread','verb','əˈbeɪt',['lessen','diminish'],['intensify'],'The storm began to abate.','ঝড়টি কমতে শুরু করল.','abatement','medium','high',['admission','synonym'],'Common Admission','Curated admission list',['reduce','mitigate']],
    ['aberration','বিচ্যুতি','a departure from what is normal or expected','noun','ˌæbəˈreɪʃən',['deviation','anomaly'],['normality'],'His rude remark was an aberration.','তার অভদ্র মন্তব্যটি ছিল একটি ব্যতিক্রম.','aberrant','hard','high',['admission','vocabulary'],'Frequently Tested','Curated admission list',['anomaly']],
    ['benevolent','দয়ালু','well meaning and kindly','adjective','bəˈnevələnt',['kind','charitable'],['malevolent','unkind'],'The benevolent donor funded the library.','দয়ালু দাতা লাইব্রেরির অর্থায়ন করলেন.','benevolence','easy','high',['character','synonym'],'Common Admission','Curated admission list',['kindness']],
    ['candid','স্পষ্টবাদী','truthful and straightforward','adjective','ˈkændɪd',['frank','honest'],['evasive','deceitful'],'She gave a candid opinion.','সে একটি স্পষ্টবাদী মতামত দিল.','candor','easy','high',['admission','synonym'],'University Admission','Curated admission list',['frank']],
    ['clandestine','গোপন','kept secret or done secretly','adjective','klænˈdestɪn',['secret',' covert'],['open','public'],'They held a clandestine meeting.','তারা একটি গোপন বৈঠক করল.','clandestinely','hard','high',['admission','advanced'],'Advanced','Curated admission list',['secret']],
    ['concur','একমত হওয়া','to agree with someone or something','verb','kənˈkɜːr',['agree','assent'],['disagree','dissent'],'I concur with your conclusion.','আমি তোমার সিদ্ধান্তের সঙ্গে একমত.','concurrence','medium','high',['synonym','verb'],'University Admission','Curated admission list',['agree']],
    ['diligent','পরিশ্রমী','having or showing care and conscientiousness','adjective','ˈdɪlɪdʒənt',['hardworking','industrious'],['lazy','negligent'],'The diligent student revised daily.','পরিশ্রমী শিক্ষার্থী প্রতিদিন পুনরাবৃত্তি করত.','diligence','easy','high',['character','admission'],'Common Admission','Curated admission list',['industrious']],
    ['eloquent','বাকপটু','fluent or persuasive in speaking or writing','adjective','ˈeləkwənt',['articulate','expressive'],['inarticulate'],'Her eloquent answer impressed the panel.','তার বাকপটু উত্তর প্যানেলকে মুগ্ধ করল.','eloquence','medium','high',['literature','admission'],'Literature','Curated admission list',['articulate']],
    ['emulate','অনুকরণ করা','to imitate someone admired','verb','ˈemjʊleɪt',['imitate','copy'],['neglect'],'Young writers emulate great authors.','তরুণ লেখকেরা মহান লেখকদের অনুকরণ করেন.','emulation','medium','medium',['verb','literature'],'Literature','Curated admission list',['imitate']],
    ['frugal','মিতব্যয়ী','sparing or economical with money or resources','adjective','ˈfruːɡəl',['thrifty','economical'],['wasteful'],'A frugal lifestyle reduces waste.','মিতব্যয়ী জীবনযাপন অপচয় কমায়.','frugality','easy','medium',['admission'],'Common Admission','Curated admission list',['thrifty']],
    ['impede','বাধা দেওয়া','to delay or prevent progress','verb','ɪmˈpiːd',['hinder','obstruct'],['facilitate','assist'],'Poor planning can impede progress.','দুর্বল পরিকল্পনা অগ্রগতিতে বাধা দিতে পারে.','impediment','medium','high',['admission','verb'],'Frequently Tested','Curated admission list',['hinder']],
    ['lucid','সুস্পষ্ট','expressed clearly; easy to understand','adjective','ˈluːsɪd',['clear','intelligible'],['confusing','obscure'],'The professor gave a lucid explanation.','অধ্যাপক একটি সুস্পষ্ট ব্যাখ্যা দিলেন.','lucidity','easy','high',['admission','synonym'],'Frequently Tested','Curated admission list',['clear']],
    ['meticulous','খুঁতখুঁতে','showing great attention to detail','adjective','məˈtɪkjələs',['careful','precise'],['careless','sloppy'],'Her meticulous notes helped revision.','তার খুঁতখুঁতে নোট পুনরাবৃত্তিতে সাহায্য করল.','meticulously','hard','high',['admission','advanced'],'Advanced','Curated admission list',['precise']],
    ['novel','নতুন; উপন্যাস','new or unusual; also a book-length fiction','adjective / noun','ˈnɒvəl',['original','fresh'],['familiar','old'],'The novel approach solved the problem.','নতুন পদ্ধতিটি সমস্যার সমাধান করল.','novelty','medium','medium',['literature','multiple meaning'],'Literature','Curated admission list',['original']],
    ['obscure','অস্পষ্ট; অখ্যাত','not clearly understood or widely known','adjective','əbˈskjʊər',['unclear','unknown'],['clear','famous'],'The reference was too obscure for beginners.','উৎসটি শিক্ষানবিশদের জন্য অত্যন্ত অস্পষ্ট ছিল.','obscurity','hard','high',['advanced','antonym'],'Advanced','Curated admission list',['unclear']],
    ['pragmatic','বাস্তববাদী','dealing with problems in a practical way','adjective','præɡˈmætɪk',['practical','realistic'],['idealistic'],'We need a pragmatic solution.','আমাদের একটি বাস্তববাদী সমাধান দরকার.','pragmatism','medium','high',['admission','character'],'University Admission','Curated admission list',['practical']],
    ['resilient','সহনশীল','able to recover quickly from difficulty','adjective','rɪˈzɪliənt',['tough','adaptable'],['fragile','vulnerable'],'Resilient learners improve after mistakes.','সহনশীল শিক্ষার্থীরা ভুলের পর উন্নতি করে.','resilience','medium','high',['admission','character'],'University Admission','Curated admission list',['adaptable']],
    ['scrutinize','সূক্ষ্মভাবে পরীক্ষা করা','to examine closely and critically','verb','ˈskruːtənaɪz',['inspect','examine'],['ignore','overlook'],'Scrutinize each option before answering.','উত্তর দেওয়ার আগে প্রতিটি বিকল্প সূক্ষ্মভাবে পরীক্ষা করো.','scrutiny','hard','high',['exam','verb'],'Frequently Tested','Curated admission list',['inspect']],
    ['substantiate','প্রমাণ করা','to provide evidence to support a claim','verb','səbˈstænʃieɪt',['prove','verify'],['refute','contradict'],'The data substantiate the claim.','তথ্যটি দাবিটির প্রমাণ দেয়.','substantiation','hard','high',['academic','advanced'],'BCS','Curated admission list',['prove']],
    ['ubiquitous','সর্বত্র বিরাজমান','present, appearing, or found everywhere','adjective','juːˈbɪkwɪtəs',['omnipresent','universal'],['rare','scarce'],'Smartphones are ubiquitous today.','আজ স্মার্টফোন সর্বত্র বিরাজমান.','ubiquity','hard','high',['advanced','BCS'],'BCS','Curated admission list',['omnipresent']],
    ['venerate','শ্রদ্ধা করা','to regard with great respect','verb','ˈvenəreɪt',['revere','honour'],['despise','disdain'],'Many venerate the poet.','অনেকে কবিকে শ্রদ্ধা করেন.','veneration','hard','medium',['literature','verb'],'Literature','Curated admission list',['revere']],
    ['versatile','বহুমুখী','able to adapt to many activities or functions','adjective','ˈvɜːsətaɪl',['adaptable','flexible'],['inflexible'],'She is a versatile performer.','সে একজন বহুমুখী শিল্পী.','versatility','medium','medium',['admission','character'],'Common Admission','Curated admission list',['flexible']],
    ['wary','সতর্ক','feeling or showing caution about possible dangers','adjective','ˈweəri',['cautious','alert'],['careless','trusting'],'Be wary of misleading options.','বিভ্রান্তিকর বিকল্প সম্পর্কে সতর্ক থাকো.','wariness','easy','high',['exam','antonym'],'Frequently Tested','Curated admission list',['cautious']],
    ['zealous','উদ্যমী','having or showing great energy or enthusiasm','adjective','ˈzeləs',['enthusiastic','passionate'],['apathetic','indifferent'],'The zealous volunteer helped everyone.','উদ্যমী স্বেচ্ছাসেবক সবাইকে সাহায্য করল.','zeal','medium','medium',['character','synonym'],'Common Admission','Curated admission list',['enthusiastic']]
  ];
  function makeSample(d){return {id:uid(),word:d[0],bengaliMeaning:d[1],meaning:d[1],definition:d[2],partOfSpeech:d[3],pronunciation:d[4],synonyms:d[5],antonyms:d[6],exampleSentence:d[7],example:d[7],bengaliExampleMeaning:d[8],wordFamily:d[9],difficulty:d[10],importance:d[11],tags:d[12],category:d[13],source:d[14],relatedWords:d[15],status:'new',correctAttempts:0,wrongAttempts:0,accuracy:0,lastPracticed:null,nextReview:null,streak:0,bookmark:false,mistake:false,mastery:0,createdAt:now()};}
  const all = () => records;
  async function refresh(){ records=await dbGetAll('vocabulary'); if(typeof CACHE!=='undefined') CACHE.vocabulary=records.slice(); return records; }
  async function save(v){ await dbPut('vocabulary',v); await refresh(); }
  function normalize(v){ v.synonyms=arr(v.synonyms); v.antonyms=arr(v.antonyms); v.tags=arr(v.tags); v.relatedWords=arr(v.relatedWords); v.bengaliMeaning=v.bengaliMeaning||v.meaning||''; v.definition=v.definition||v.meaning||''; v.exampleSentence=v.exampleSentence||v.example||''; v.correctAttempts=Number(v.correctAttempts||0); v.wrongAttempts=Number(v.wrongAttempts||0); v.accuracy=v.correctAttempts+v.wrongAttempts?Math.round(v.correctAttempts/(v.correctAttempts+v.wrongAttempts)*100):0; v.mastery=Number(v.mastery||0); v.status=v.status||'new'; return v; }
  async function seed(){ await refresh(); if(all().length) return; for(const d of samples) await save(makeSample(d)); await refresh(); }
  function status(v){return normalize(v).status.toUpperCase();}
  function updateMastery(v, correct){ normalize(v); if(correct){v.correctAttempts++;v.streak++;v.mastery=Math.min(100,v.mastery+Math.max(8, v.streak*4));}else{v.wrongAttempts++;v.streak=0;v.mastery=Math.max(0,v.mastery-4);v.mistake=true;} v.accuracy=Math.round(v.correctAttempts/(v.correctAttempts+v.wrongAttempts)*100); v.lastPracticed=now(); v.nextReview=now()+ (correct?Math.max(1,Math.min(7,v.streak))*86400000:3600000); v.status=v.mastery>=90?'mastered':v.mastery>=70?'familiar':v.mastery>=35?'practicing':(v.correctAttempts||v.wrongAttempts)?'learning':'new'; return v; }
  const text=v=>[v.word,v.bengaliMeaning,v.definition,...v.synonyms,...v.antonyms,...v.tags].join(' ').toLocaleLowerCase();
  function metric(){const xs=all().map(normalize), total=xs.length, mastered=xs.filter(x=>x.status==='mastered').length, learning=xs.filter(x=>['learning','practicing','familiar'].includes(x.status)).length, fresh=xs.filter(x=>x.status==='new').length, accuracy=total?Math.round(xs.reduce((n,x)=>n+x.accuracy,0)/total):0, mastery=total?Math.round(xs.reduce((n,x)=>n+x.mastery,0)/total):0; return {total,mastered,learning,new:fresh,accuracy,mastery,streak:Math.max(0,...xs.map(x=>x.streak))};}
  const card=v=>`<article class="vm-card"><div class="vm-card-top"><div><div class="vm-word">${esc(v.word)}</div><div class="vm-pron">/${esc(v.pronunciation||'—')}/ · ${esc(v.partOfSpeech||'word')}</div></div><button class="vm-bookmark" onclick="VocabularyMaster.toggleBookmark('${v.id}')">${v.bookmark?'★':'☆'}</button></div><div class="vm-meaning">${esc(v.bengaliMeaning)}</div><div class="vm-card-foot"><span class="vm-status vm-${v.status}">${status(v)}</span><span>${v.accuracy}% accuracy</span><button class="vm-link" onclick="VocabularyMaster.detail('${v.id}')">View details →</button></div></article>`;
  function shell(inner,title='Vocabulary Master'){ renderShell(`<div class="vm-page">${inner}</div>`,{title,back:"navigate('dashboard')"}); }
  function dashboard(){const m=metric(); const ring=`<div class="vm-ring" style="--p:${m.mastery*3.6}deg"><div><strong>${m.mastery}%</strong><small>mastery</small></div></div>`; shell(`<header class="vm-hero"><div><div class="vm-kicker">Premium learning system</div><h1>Vocabulary Master</h1><p>Build admission-ready word power with deliberate practice.</p></div><button class="vm-primary" onclick="navigate('vocabulary/library')">Open library</button></header><div class="vm-stats"><div><strong>${m.total}</strong><span>Total Words</span></div><div><strong>${m.mastered}</strong><span>Mastered</span></div><div><strong>${m.learning}</strong><span>Learning</span></div><div><strong>${m.new}</strong><span>New</span></div><div><strong>${m.accuracy}%</strong><span>Accuracy</span></div><div><strong>🔥 ${m.streak}</strong><span>Current Streak</span></div></div><section class="vm-progress-card">${ring}<div><div class="vm-kicker">Your vocabulary journey</div><h2>${m.mastered} words mastered</h2><p>Mastery grows from repeated correct answers, not from simply marking a word learned.</p><button class="vm-secondary" onclick="navigate('vocabulary/practice')">Start practice →</button></div></section><section class="vm-today"><div><div class="vm-kicker">Today’s practice</div><h2>20 new + 10 revision words</h2><p>${m.total?`Keep your review loop active across ${m.total} words.`:'Your sample library is being prepared.'}</p></div><button class="vm-primary" onclick="VocabularyMaster.startPractice()">Start Today’s Practice →</button></section><div class="vm-quick"><button onclick="navigate('vocabulary/library')">▤<span>Library</span></button><button onclick="navigate('vocabulary/practice')">◉<span>Practice</span></button><button onclick="navigate('vocabulary/exam')">▣<span>Exam</span></button><button onclick="navigate('vocabulary/mistakes')">△<span>Mistakes</span></button><button onclick="VocabularyMaster.setFilter('bookmarked')">★<span>Bookmarked</span></button><button onclick="navigate('vocabulary/progress')">↗<span>Progress</span></button></div></div>`);
  }
  function library(){let xs=all().map(normalize); const q=state.search.trim().toLocaleLowerCase(); if(q)xs=xs.filter(v=>text(v).includes(q)); if(state.filter==='bookmarked')xs=xs.filter(v=>v.bookmark); else if(state.filter==='mistakes')xs=xs.filter(v=>v.mistake); else if(state.filter!=='all')xs=xs.filter(v=>v.status===state.filter); if(state.category!=='All')xs=xs.filter(v=>v.category===state.category); const cats=['All','Common Admission','University Admission','Frequently Tested','BCS','Literature','Advanced']; shell(`<header class="vm-hero vm-compact"><div><div class="vm-kicker">Central vocabulary database</div><h1>Vocabulary Library</h1><p>Search every word, meaning, synonym, antonym, and tag from one source.</p></div><button class="vm-primary" onclick="VocabularyMaster.startPractice()">Practice</button></header><div class="vm-search"><input value="${esc(state.search)}" oninput="VocabularyMaster.search(this.value)" placeholder="Search English, বাংলা meaning, synonyms, tags…"></div><div class="vm-chips">${['all','new','learning','practicing','familiar','mastered','bookmarked','mistakes'].map(k=>`<button class="${state.filter===k?'active':''}" onclick="VocabularyMaster.setFilter('${k}')">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div><div class="vm-chips vm-category">${cats.map(k=>`<button class="${state.category===k?'active':''}" onclick="VocabularyMaster.setCategory('${k}')">${k}</button>`).join('')}</div><div class="vm-list-head"><b>${xs.length} words</b><span>Cards update after every answer</span></div><div class="vm-list">${xs.length?xs.map(card).join(''):`<div class="vm-empty"><strong>No words match these filters.</strong><p>Try another search or reset the filters.</p><button class="vm-secondary" onclick="VocabularyMaster.setFilter('all')">Show all words</button></div>`}</div>`,'Vocabulary Library');}
  function detail(id){const v=all().map(normalize).find(x=>x.id===id); if(!v)return library(); state.detail=id; shell(`<button class="vm-back" onclick="navigate('vocabulary/library')">← Back to library</button><article class="vm-detail"><div class="vm-card-top"><div><div class="vm-kicker">${esc(v.category)} · ${esc(v.difficulty)}</div><h1>${esc(v.word)}</h1><div class="vm-pron">/${esc(v.pronunciation||'—')}/ · ${esc(v.partOfSpeech)}</div></div><button class="vm-bookmark" onclick="VocabularyMaster.toggleBookmark('${v.id}')">${v.bookmark?'★':'☆'}</button></div><div class="vm-status vm-${v.status}">${status(v)}</div><div class="vm-detail-grid"><div><b>বাংলা অর্থ</b><p>${esc(v.bengaliMeaning)}</p></div><div><b>English definition</b><p>${esc(v.definition)}</p></div><div><b>Synonyms</b><p>${v.synonyms.map(x=>`<span class="vm-chip">${esc(x)}</span>`).join('')}</p></div><div><b>Antonyms</b><p>${v.antonyms.map(x=>`<span class="vm-chip vm-chip-red">${esc(x)}</span>`).join('')}</p></div><div><b>Example</b><p><i>${esc(v.exampleSentence)}</i><br><span class="vm-bengali">${esc(v.bengaliExampleMeaning)}</span></p></div><div><b>Word family</b><p>${esc(v.wordFamily||'—')}</p></div></div><div class="vm-detail-meta">${v.correctAttempts} correct · ${v.wrongAttempts} wrong · ${v.accuracy}% accuracy · ${v.mastery}% mastery</div><div class="vm-actions"><button class="vm-primary" onclick="VocabularyMaster.markLearned('${v.id}')">Mark as learned</button><button class="vm-secondary" onclick="VocabularyMaster.practiceOne('${v.id}')">Practice again</button><button class="vm-secondary" onclick="VocabularyMaster.markMistake('${v.id}')">Add to mistakes</button></div></article>`,'Word Details');}
  function setup(kind){const exam=kind==='exam'; shell(`<header class="vm-hero vm-compact"><div><div class="vm-kicker">${exam?'Vocabulary exam':'Adaptive practice'}</div><h1>${exam?'Vocabulary Exam':'Practice setup'}</h1><p>${exam?'A separate test from the main Admission Exam.':'Choose a focused recall session and receive feedback after every answer.'}</p></div></header><div class="vm-setup"><label>Number of words<select id="vmCount">${(exam?[10,20,50,100]:[10,20,30,50]).map(n=>`<option>${n}</option>`).join('')}</select></label><label>Question type<select id="vmType"><option value="mixed">Mixed</option><option value="meaning">Word → Meaning</option><option value="word">Meaning → Word</option><option value="synonym">Synonym</option><option value="antonym">Antonym</option></select></label><label>Difficulty<select id="vmDiff"><option value="all">All difficulties</option><option>easy</option><option>medium</option><option>hard</option></select></label><button class="vm-primary" onclick="VocabularyMaster.begin('${kind}')">${exam?'Start exam':'Start practice'} →</button></div>`,'Vocabulary '+(exam?'Exam':'Practice'));}
  function begin(kind){const count=Number(document.getElementById('vmCount').value), type=document.getElementById('vmType').value, diff=document.getElementById('vmDiff').value; let pool=all().map(normalize).filter(v=>diff==='all'||v.difficulty===diff); if(!pool.length)pool=all().map(normalize); pool=pool.sort(()=>Math.random()-.5).slice(0,Math.min(count,pool.length)); state.practice=null; state.exam=null; state[kind]={kind,words:pool,index:0,score:0,answers:[],type,started:now()}; renderSession(kind);}
  function options(v,type){let correct=type==='word'?v.word:type==='synonym'?v.synonyms[0]:type==='antonym'?v.antonyms[0]:v.bengaliMeaning; let pool=all().map(x=>normalize(x)); let candidates=type==='word'?pool.map(x=>x.word):type==='synonym'?pool.flatMap(x=>x.synonyms):type==='antonym'?pool.flatMap(x=>x.antonyms):pool.map(x=>x.bengaliMeaning); return [...new Set([correct,...candidates.filter(x=>x&&x!==correct).sort(()=>Math.random()-.5).slice(0,3)])].sort(()=>Math.random()-.5);}
  function renderSession(kind){const s=state[kind]; if(!s||s.index>=s.words.length)return result(kind); const v=s.words[s.index], type=s.type==='mixed'?['meaning','word','synonym','antonym'][s.index%4]:s.type, prompt=type==='word'?v.bengaliMeaning:`${v.word} — ${type==='synonym'?'choose a synonym':type==='antonym'?'choose an antonym':'choose the Bengali meaning'}`, opts=options(v,type); s.current={v,type,opts}; shell(`<div class="vm-session-head"><button class="vm-back" onclick="navigate('vocabulary')">× Exit</button><span>${kind==='exam'?'Exam':'Practice'} · ${s.index+1}/${s.words.length}</span><b>Score ${s.score}</b></div><div class="vm-progress"><i style="width:${((s.index)/s.words.length)*100}%"></i></div><article class="vm-question"><div class="vm-kicker">${type.toUpperCase()}</div><h1>${esc(prompt)}</h1>${type!=='word'?`<div class="vm-pron">/${esc(v.pronunciation||'—')}/</div>`:''}<div class="vm-options">${opts.map(o=>`<button onclick='VocabularyMaster.answer(${esc(JSON.stringify(o))})'>${esc(o)}</button>`).join('')}</div></article>`,'Vocabulary '+(kind==='exam'?'Exam':'Practice'));}
  async function answer(choice){const kind=state.practice?'practice':'exam',s=state[kind], {v,type,opts}=s.current; const correct=type==='word'?v.word:type==='synonym'?v.synonyms[0]:type==='antonym'?v.antonyms[0]:v.bengaliMeaning; const ok=choice===correct; updateMastery(v,ok); await save(v); if(ok)s.score++; s.answers.push({word:v.word,choice,correct,ok,type}); if(ok&&typeof grantActivity==='function')grantActivity({type:'Vocabulary Practice',questions:1,gold:2,eventId:`vocab-${kind}-${v.id}-${s.index}-${Date.now()}`}).catch(()=>{}); openModal(`<div class="vm-feedback ${ok?'good':'bad'}"><h2>${ok?'Correct':'Review this one'}</h2><p><b>${esc(v.word)}</b></p><p>Your answer: ${esc(choice)}</p>${!ok?`<p>Correct answer: <b>${esc(correct)}</b></p>`:''}<button class="vm-primary" onclick="closeModal();VocabularyMaster.next()">${s.index+1<s.words.length?'Next word':'See results'} →</button></div>`);}
  function next(){const kind=state.practice?'practice':'exam',s=state[kind];s.index++;renderSession(kind);}
  function result(kind){const s=state[kind], total=s.words.length, accuracy=total?Math.round(s.score/total*100):0; if(kind==='exam'&&typeof grantActivity==='function')grantActivity({type:'Vocabulary Exam',questions:total,gold:Math.max(5,Math.round(accuracy/10)),eventId:`vocab-exam-${s.started}`}).catch(()=>{}); shell(`<div class="vm-result"><div class="vm-kicker">${kind==='exam'?'Exam complete':'Practice complete'}</div><h1>${s.score}/${total}</h1><p class="vm-result-accuracy">${accuracy}% accuracy</p><div class="vm-stats"><div><strong>${s.answers.filter(x=>x.type==='synonym'&&x.ok).length}</strong><span>Synonym %</span></div><div><strong>${s.answers.filter(x=>x.type==='antonym'&&x.ok).length}</strong><span>Antonym correct</span></div><div><strong>${s.answers.filter(x=>!x.ok).length}</strong><span>Needs review</span></div></div><div class="vm-actions"><button class="vm-primary" onclick="VocabularyMaster.startPractice()">Practice again</button><button class="vm-secondary" onclick="navigate('vocabulary/mistakes')">Review mistakes</button></div></div>`,'Vocabulary Results');}
  function mistakes(){const xs=all().map(normalize).filter(v=>v.mistake); shell(`<header class="vm-hero vm-compact"><div><div class="vm-kicker">Focused revision</div><h1>Mistake Review</h1><p>Incorrect answers stay connected to the central vocabulary record.</p></div></header>${xs.length?xs.map(v=>`<article class="vm-card"><div class="vm-card-top"><div><div class="vm-word">${esc(v.word)}</div><div class="vm-meaning">${esc(v.bengaliMeaning)}</div></div><span class="vm-status vm-${v.status}">${v.wrongAttempts} wrong</span></div><div class="vm-card-foot"><span>${v.accuracy}% accuracy</span><button class="vm-link" onclick="VocabularyMaster.practiceOne('${v.id}')">Practice again →</button></div></article>`).join(''):`<div class="vm-empty"><strong>No vocabulary mistakes yet.</strong><p>Complete a practice session to build your review list.</p></div>`}`,'Mistake Review');}
  function progress(){const m=metric(), xs=all().map(normalize); shell(`<header class="vm-hero vm-compact"><div><div class="vm-kicker">Mastery analytics</div><h1>Vocabulary Progress</h1><p>Performance is calculated from actual answer history.</p></div></header><section class="vm-progress-card"><div class="vm-ring" style="--p:${m.mastery*3.6}deg"><div><strong>${m.mastery}%</strong><small>mastery</small></div></div><div><h2>Keep the review loop alive</h2><p>${xs.reduce((n,v)=>n+v.correctAttempts,0)} correct answers across ${m.total} words.</p><div class="vm-bar"><i style="width:${m.mastery}%"></i></div></div></section><div class="vm-stats"><div><strong>${xs.filter(v=>v.status==='mastered').length}</strong><span>Mastered</span></div><div><strong>${xs.filter(v=>v.status==='familiar').length}</strong><span>Familiar</span></div><div><strong>${xs.filter(v=>v.status==='practicing').length}</strong><span>Practicing</span></div><div><strong>${xs.filter(v=>v.status==='learning').length}</strong><span>Learning</span></div></div>`,'Vocabulary Progress');}
  async function toggleBookmark(id){const v=all().find(x=>x.id===id);if(!v)return;v.bookmark=!v.bookmark;await save(v);render();}
  async function markLearned(id){const v=all().find(x=>x.id===id);if(!v)return;v.mastery=Math.max(v.mastery||0,35);v.status='learning';await save(v);render();}
  async function markMistake(id){const v=all().find(x=>x.id===id);if(!v)return;v.mistake=true;await save(v);render();}
  function practiceOne(id){const v=all().find(x=>x.id===id);state.practice={kind:'practice',words:[v],index:0,score:0,answers:[],type:'meaning',started:now()};renderSession('practice');}
  function startPractice(){setup('practice');}
  function init(){
    const previousDashboard=window.renderDashboard;
    if(typeof previousDashboard==='function'){ window.renderDashboard=function(){ const out=previousDashboard.apply(this,arguments); setTimeout(()=>{ const page=document.querySelector('#app .page'); if(page&&!page.querySelector('[data-vocabulary-tool]')){ const item=document.createElement('div'); item.setAttribute('data-vocabulary-tool','true'); item.className='card'; item.style.cssText='cursor:pointer;border-left:4px solid var(--emerald);margin-top:10px'; item.innerHTML='<div class="row between"><div><b>📚 Vocabulary Master</b><div class="muted">Premium word practice, exams, and mastery tracking</div></div><span>›</span></div>'; item.onclick=()=>navigate('vocabulary'); page.appendChild(item); } },0); return out; }; }
    const oldRender=window.render;
    window.render=function(){const p=String(Router.path||'dashboard'); if(p==='vocabulary'||p==='vocabulary/dashboard')return dashboard(); if(p==='vocabulary/library')return library(); if(p==='vocabulary/mistakes')return mistakes(); if(p==='vocabulary/progress')return progress(); if(p==='vocabulary/practice')return setup('practice'); if(p==='vocabulary/exam')return setup('exam'); if(p.startsWith('vocabulary/word/'))return detail(p.split('/').pop()); return oldRender.apply(this,arguments);};
    V.toggleBookmark=toggleBookmark;V.markLearned=markLearned;V.markMistake=markMistake;V.practiceOne=practiceOne;V.startPractice=startPractice;V.begin=begin;V.answer=answer;V.next=next;V.detail=id=>{state.detail=id;detail(id)};V.search=s=>{state.search=s;library()};V.setFilter=k=>{state.filter=k; if(k==='bookmarked'||k==='mistakes')return library();library()};V.setCategory=k=>{state.category=k;library()};
    const waitForDb=async()=>{ for(let i=0;i<40;i++){ if(typeof DB!=='undefined'&&DB) return true; await new Promise(r=>setTimeout(r,100)); } return false; };
    (async()=>{try{if(await waitForDb()){await seed(); if(Router.path&&Router.path.startsWith('vocabulary'))render();}}catch(e){console.error('Vocabulary seed failed',e);}})();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
